version: "3.9"

services:
  redis:
    container_name: redis
    image: redis:7.2.3-alpine3.19
    restart: on-failure
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      # - ./redis-snapshot.rdb:/data/dump.rdb
      # - ~/.redis:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:0.8.1
    restart: on-failure
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
