version: "3.9"

services:
  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local:2.2.0
    restart: on-failure
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
      - "dynamodb-data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  dynamodb-admin:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local

volumes:
  dynamodb-data:
